# videorag_project/configs/logging_config.yaml

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"
  json:
    # Requires python-json-logger to be installed
    # Useful for log aggregation systems like ELK or Splunk
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    class: "pythonjsonlogger.jsonlogger.JsonFormatter"

handlers:
  console:
    class: "logging.StreamHandler"
    level: "INFO"
    formatter: "standard"
    stream: "ext://sys.stdout"
  
  file_handler:
    class: "logging.handlers.RotatingFileHandler"
    level: "DEBUG"
    formatter: "standard"
    filename: "logs/app.log"
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: "utf8"

loggers:
  # Logger for our specific application
  __main__:
    level: "INFO"
    handlers: [console, file_handler]
    propagate: no
  api:
    level: "INFO"
    handlers: [console, file_handler]
    propagate: no
  indexing:
    level: "INFO"
    handlers: [console, file_handler]
    propagate: no
  core:
    level: "INFO"
    handlers: [console, file_handler]
    propagate: no
  
  # Control verbosity of third-party libraries
  uvicorn.error:
    level: "INFO"
  uvicorn.access:
    level: "WARNING" # Silence access logs for less noise
  neo4j:
    level: "WARNING"
  httpx: # Used by OpenAI client
    level: "WARNING"

root:
  level: "WARNING"
  handlers: [console]